# Generated by Django 5.2 on 2025-05-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='countries',
            field=models.ManyToManyField(to='settings.country'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='delivery_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycompany'),
        ),
    ]
