# Generated by Django 5.0.2 on 2025-09-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverycompany_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_areas', models.JSONField(default=list, help_text='List of preferred delivery areas')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], default='motorcycle', max_length=20)),
                ('max_package_weight', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum package weight in kg', max_digits=5)),
                ('start_time', models.TimeField(default='08:00', help_text='Preferred start time')),
                ('end_time', models.TimeField(default='18:00', help_text='Preferred end time')),
                ('accept_urgent_deliveries', models.BooleanField(default=True, help_text='Accept urgent deliveries outside normal hours')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable notifications for new orders')),
                ('auto_accept_orders', models.BooleanField(default=False, help_text='Automatically accept assigned orders')),
                ('max_daily_deliveries', models.PositiveIntegerField(default=20, help_text='Maximum deliveries per day')),
                ('preferred_delivery_radius', models.PositiveIntegerField(default=10, help_text='Preferred delivery radius in km')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Preferences',
                'verbose_name_plural': 'Delivery Preferences',
            },
        ),
    ]
