# Generated by Django 5.2.7 on 2025-11-11 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_orderassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='manager_confirmation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=20, null=True, verbose_name='Manager Confirmation Status'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='manager_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manager Confirmed At'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='manager_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Manager Confirmed By'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Manager Rejection Reason'),
        ),
    ]
