# Generated by Django 5.0.2 on 2025-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='account holder name'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='account number (IBAN)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='user',
            name='iban_confirmation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN confirmation'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/', verbose_name='ID back image'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/', verbose_name='ID front image'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='marketing platforms'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_link',
            field=models.URLField(blank=True, null=True, verbose_name='store link'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='store name'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='store specialization'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('specialized', 'Specialized')], max_length=50, null=True, verbose_name='store type'),
        ),
    ]
