# Generated by Django 5.2.6 on 2025-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_loginattempt_user2faprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'login attempt', 'verbose_name_plural': 'login attempts'},
        ),
        migrations.AlterModelOptions(
            name='user2faprofile',
            options={'verbose_name': '2FA profile', 'verbose_name_plural': '2FA profiles'},
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='failure reason'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='success',
            field=models.BooleanField(default=False, verbose_name='success'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='user2faprofile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='backup codes'),
        ),
        migrations.AlterField(
            model_name='user2faprofile',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA enabled'),
        ),
    ]
