# Generated by Django 5.2.8 on 2025-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_mark_existing_users_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_change_required",
            field=models.BooleanField(
                default=False, verbose_name="password change required"
            ),
        ),
    ]
