# Generated by Django 5.0.2 on 2025-08-02 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_product_options_alter_product_code'),
        ('stock_keeper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockkeepersession',
            options={'ordering': ['-shift_start'], 'verbose_name': 'Stock Keeper Session', 'verbose_name_plural': 'Stock Keeper Sessions'},
        ),
        migrations.AddField(
            model_name='stockkeepersession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockkeepersession',
            name='items_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockkeepersession',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockkeepersession',
            name='session_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockkeepersession',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PhysicalCountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_session_id', models.CharField(max_length=50)),
                ('location_code', models.CharField(blank=True, max_length=50)),
                ('system_quantity', models.PositiveIntegerField()),
                ('counted_quantity', models.PositiveIntegerField()),
                ('variance', models.IntegerField()),
                ('condition_status', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('defective', 'Defective'), ('missing', 'Missing')], default='good', max_length=20)),
                ('count_notes', models.TextField(blank=True)),
                ('count_timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('adjustment_applied', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_counts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_keeper.warehouse')),
            ],
            options={
                'verbose_name': 'Physical Count Record',
                'verbose_name_plural': 'Physical Count Records',
                'ordering': ['-count_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockKeeperTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('receive', 'Receive Stock'), ('ship', 'Ship Orders'), ('transfer', 'Transfer Stock'), ('count', 'Cycle Count'), ('adjustment', 'Stock Adjustment'), ('maintenance', 'Maintenance')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_keeper.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Keeper Task',
                'verbose_name_plural': 'Stock Keeper Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('product_lookup', 'Product Lookup'), ('stock_update', 'Stock Update'), ('receive', 'Receive Stock'), ('ship', 'Ship Orders'), ('transfer', 'Transfer Stock'), ('count', 'Cycle Count')], max_length=20)),
                ('barcode_data', models.CharField(max_length=255)),
                ('scan_result', models.CharField(choices=[('success', 'Success'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=20)),
                ('quantity_change', models.IntegerField(default=0)),
                ('location_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_keeper.warehouse')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_keeper.stockkeepertask')),
            ],
            options={
                'verbose_name': 'Barcode Scan History',
                'verbose_name_plural': 'Barcode Scan History',
                'ordering': ['-scan_timestamp'],
            },
        ),
    ]
