# Generated by Django 5.2.4 on 2025-08-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('stock_keeper', '0002_alter_stockkeepersession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockkeepersession',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_keeper_outgoing_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_keeper_incoming_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='trackingnumber',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='barcodescanhistory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockkeepertask',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='physicalcountrecord',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
