# Generated by Django 4.2.25 on 2025-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_keeper', '0003_alter_stockkeepersession_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcountrecord',
            name='counted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalcountrecord',
            name='system_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalcountrecord',
            name='variance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
