# Generated by Django 5.0.2 on 2025-08-02 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_payment_options_payment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('amazon_seller', 'Amazon Seller Central'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('woocommerce', 'WooCommerce'), ('etsy', 'Etsy'), ('ebay', 'eBay'), ('other', 'Other')], max_length=50, verbose_name='platform name')),
                ('store_name', models.CharField(max_length=200, verbose_name='store name')),
                ('store_url', models.URLField(blank=True, null=True, verbose_name='store URL')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API key')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API secret')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='refresh token')),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='merchant ID')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='webhook URL')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Verification'), ('error', 'Connection Error')], default='pending', max_length=20, verbose_name='status')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='last sync')),
                ('sync_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='sync frequency')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='auto sync')),
                ('sync_orders', models.BooleanField(default=True, verbose_name='sync orders')),
                ('sync_payments', models.BooleanField(default=True, verbose_name='sync payments')),
                ('sync_inventory', models.BooleanField(default=False, verbose_name='sync inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment platform',
                'verbose_name_plural': 'payment platforms',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform_name', 'store_name')},
            },
        ),
        migrations.CreateModel(
            name='PlatformSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('orders', 'Orders'), ('payments', 'Payments'), ('inventory', 'Inventory'), ('products', 'Products'), ('customers', 'Customers')], max_length=20, verbose_name='sync type')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success'), ('pending', 'Pending')], max_length=20, verbose_name='status')),
                ('records_processed', models.IntegerField(default=0, verbose_name='records processed')),
                ('records_synced', models.IntegerField(default=0, verbose_name='records synced')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='finance.paymentplatform')),
            ],
            options={
                'verbose_name': 'platform sync log',
                'verbose_name_plural': 'platform sync logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
