# Generated by Django 5.2.4 on 2025-07-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_alter_agentperformance_options_alter_calllog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callcenteragent',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='callcenteragent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerinteraction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='customerinteraction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='managernote',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='managernote',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managernote',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='teamperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teamperformance',
            name='top_performer_agent',
        ),
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='call_recording_url',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='customer_satisfaction',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='escalation_reason',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='resolution_status',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='customer_satisfaction_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Customer Satisfaction'),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AgentSession',
        ),
        migrations.DeleteModel(
            name='CallCenterAgent',
        ),
        migrations.DeleteModel(
            name='CustomerInteraction',
        ),
        migrations.DeleteModel(
            name='ManagerNote',
        ),
        migrations.DeleteModel(
            name='OrderAssignment',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='TeamPerformance',
        ),
    ]
