# Generated by Django 5.2.4 on 2025-08-02 13:20

import sellers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sellers.models.product_image_path),
        ),
    ]
