# Generated by Django 5.0.2 on 2025-08-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(editable=False, help_text='Auto-generated SKU/Product Code', max_length=50, unique=True),
        ),
    ]
