# Generated by Django 5.2.4 on 2025-08-11 10:26

import django.db.models.deletion
import django.utils.timezone
import sellers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_product_approved_at_product_approved_by_and_more'),
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleschannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sales Channel', 'verbose_name_plural': 'Sales Channels'},
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sellers.models.product_image_path, verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Product Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Product Name (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, verbose_name='Product Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='api_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Channel Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Channel Name (English)'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='url',
            field=models.URLField(verbose_name='Channel URL'),
        ),
    ]
