# Generated by Django 5.2.4 on 2025-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_alter_saleschannel_options_saleschannel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleschannel',
            options={'ordering': ['-id'], 'verbose_name': 'Sales Channel', 'verbose_name_plural': 'Sales Channels'},
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, null=True, verbose_name='Product Link'),
        ),
    ]
