# Generated by Django 5.2.4 on 2025-08-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_product_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerNotification',
        ),
    ]
