# Generated by Django 5.0.2 on 2025-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_delete_sellernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
    ]
