# Generated by Django 5.0.2 on 2025-09-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('sellers', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
    ]
