# Generated by Django 5.0.2 on 2025-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0016_productdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.CharField(blank=True, help_text='e.g., Red Large, Blue Small, etc.', max_length=200, null=True, verbose_name='Product Variant'),
        ),
    ]
