# Generated by Django 4.2.25 on 2025-11-26 16:01

import cloudinary_storage.storage
from django.db import migrations, models
import sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0017_product_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=sellers.models.product_image_path, verbose_name='Product Image'),
        ),
    ]
