# Generated by Django 5.2 on 2025-05-12 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='settings.country'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='countries',
            field=models.ManyToManyField(related_name='delivery_companies', to='settings.country'),
        ),
    ]
