# Generated by Django 5.2 on 2025-05-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'sourcing comment',
                'verbose_name_plural': 'sourcing comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='request number')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('carton_quantity', models.PositiveIntegerField(verbose_name='carton quantity')),
                ('unit_quantity', models.PositiveIntegerField(default=0, help_text='Number of units per carton', verbose_name='unit quantity')),
                ('total_units', models.PositiveIntegerField(default=0, verbose_name='total units')),
                ('source_country', models.CharField(max_length=100, verbose_name='source country')),
                ('destination_country', models.CharField(max_length=100, verbose_name='destination country')),
                ('finance_source', models.CharField(choices=[('seller', 'Seller Account'), ('company', 'Company Account')], max_length=20, verbose_name='finance source')),
                ('supplier_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='supplier contact')),
                ('supplier_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='supplier phone')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost per unit')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total cost')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='shipping cost')),
                ('customs_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='customs fees')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='grand total')),
                ('currency', models.CharField(default='AED', max_length=3, verbose_name='currency')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='weight (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='dimensions')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='tracking number')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='estimated arrival')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='actual arrival')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10, verbose_name='priority')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('quality_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='quality rating')),
                ('delivery_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='delivery rating')),
                ('price_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='price rating')),
            ],
            options={
                'verbose_name': 'sourcing request',
                'verbose_name_plural': 'sourcing requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('shipping_label', 'Shipping Label'), ('product_image', 'Product Image'), ('customs_document', 'Customs Document'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='sourcing_documents/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'sourcing request document',
                'verbose_name_plural': 'sourcing request documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('quality_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='quality score')),
                ('delivery_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='delivery score')),
                ('price_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='price score')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
