# Generated by Django 5.2 on 2025-05-12 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_initial'),
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sourcing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_requests', to='sellers.product'),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcingcomment',
            name='sourcing_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sourcing.sourcingrequest'),
        ),
        migrations.AddField(
            model_name='sourcingrequestdocument',
            name='sourcing_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sourcing.sourcingrequest'),
        ),
        migrations.AddField(
            model_name='sourcingrequestdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sourcing_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourcing_requests', to='sourcing.supplier'),
        ),
    ]
