# Generated by Django 5.2.4 on 2025-07-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(default='General', max_length=50, verbose_name='category'),
        ),
    ]
