# Generated by Django 5.2.3 on 2025-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_add_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='finance_source',
            field=models.CharField(choices=[('self_financed', 'Self Financed'), ('bank_loan', 'Bank Loan'), ('investor', 'Investor'), ('seller', 'Seller Account'), ('company', 'Company Account')], max_length=20, verbose_name='finance source'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority'),
        ),
    ]
