# Generated by Django 5.2.7 on 2025-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0004_alter_sourcingrequest_finance_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='sourcing_products/', verbose_name='product image'),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='product_url',
            field=models.URLField(blank=True, help_text='Link to product page', max_length=500, null=True, verbose_name='product url'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='carton_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of cartons', verbose_name='carton quantity'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='unit_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of units/pieces per carton', verbose_name='unit quantity'),
        ),
    ]
