# Generated by Django 4.2.25 on 2025-11-26 16:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0005_sourcingrequest_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sourcing_products/', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='unit_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of units/pieces', verbose_name='unit quantity'),
        ),
    ]
