# -*- coding: utf-8 -*-
"""
Complete Emirates and Regions Data for UAE
Based on official government data
"""

EMIRATES_AND_REGIONS = {
    'abu_dhabi': {
        'name_ar': 'أبو ظبي',
        'name_en': 'Abu Dhabi',
        'regions': [
            'Al Shawamekh', 'Al Wathba North', 'Al Wathba South', 'Baniyas', 'Al Mafraq',
            'Al Mafraq Industrial', 'Bawabat Al Sharq', 'Sir Baniyas Island', 'Al Nahda Military',
            'Al Shamkha', 'Al Shamkha East', 'Al Shamkha South', 'Al Reef', 'Al Adla',
            'Rawdat Al Reef', 'Al Faya', 'Al Haffar', 'Al Me-Rad', 'Al Dhafra Air Base',
            'Icad', 'Icad Residential City', 'Mbz', 'Mina Zayed', 'Mohammed Bin Zayed City (Mbz)',
            'Mussafah', 'Mahwi', 'Esnaad', 'Khalifa City', 'Abu Dhabi International Airport',
            'Al Forsan Village', 'Al Raha Beach', 'Al Raha Gardens', 'Yas Island', 'Al Muneera',
            'Al Matar', 'Masdar City', 'Taweelah', 'Abu Al Habel Island', 'Al Bandar',
            'Al Jubail Island', 'Al Lissaily', 'Al Rayyana', 'Al Seef', 'Al Zeina',
            'Fahid Island', 'Golf Gardens', 'Watani Villas', 'Al Buteen', 'Al Khalidiyah',
            'Corniche', 'Saadiyat Island', 'Al Hosn', 'Al Khubeirah', 'Al Manhal',
            'Al Zahraa', 'Dolphin Island', 'Lulu Island', 'Qasr Al Amouage', 'Al Baladiya',
            'Al Danah (Madinat Zayed)', 'Al Muroor', 'Al Nahyan', 'Al Mina', 'Madinat Zayed',
            'Al Reem Island', 'Al Reem Island East', 'Al Maryah Island', 'Al Markaziyah',
            'Al Dana', 'Al Dhafrah', 'Al Zahiyah (Tourist Club)', 'Al Gurm', 'Al Wahdah',
            'Zayed City', 'Al Aman', 'Al Ittihad', 'Sas Al Nakhl', 'Sas Al Nakhl Village',
            'Al Karamah', 'Al Mushrif', 'Al Madina Al Riyadiya', 'Abu Dhabi Gate City',
            'Al Maqta - Abu Dhabi City', 'Al Rowdah', 'Al Safarat', 'Zayed Military City',
            'Qasr Al Shatie', 'Al Hudayriat Island', 'Al Mazoon', 'Al Mussala', 'Al Rehhan',
            'Al Tabbiyah', 'Hadbat Al Zaafran', 'Mangrove Village', 'Seashore Villas'
        ]
    },
    'dubai': {
        'name_ar': 'دبي',
        'name_en': 'Dubai',
        'regions': [
            'Abu Baker Al Siddique Road', 'Abu Hail', 'Acacia Avenues', 'Ain Khatt', 'Akoya',
            'Akoya Oxygen', 'Al Aweer', 'Al Badaa', 'Al Baraha', 'Al Barsha', 'Al Barsha South 1',
            'Al Barsha South 2', 'Al Barsha South 3', 'Al Buteen', 'Al Daghaya', 'Al Diyafah Street',
            'Al Falaj Villas', 'Al Fahidi', 'Al Furjan', 'Al Garhoud', 'Al Ghurair', 'Al Habtoor City',
            'Al Hamriya', 'Al Hudaiba', 'Al Jaddaf', 'Al Jafiliya', 'Al Juwais', 'Al Karama',
            'Al Khabaisi', 'Al Khail Gate', 'Al Khawaneej', 'Al Kifaf', 'Al Lisaili', 'Al Mafyar',
            'Al Mahra', 'Al Majara', 'Al Maktoum Road', 'Al Mamzar', 'Al Manara', 'Al Mankhool',
            'Al Marjan Island', 'Al Mizhar', 'Al Murar', 'Al Muteena', 'Al Nahda', 'Al Qarah',
            'Al Qudra', 'Al Qusais', 'Al Qusais Industrial Area', 'Al Quoz', 'Al Raffa', 'Al Ras',
            'Al Rashidiya', 'Al Rigga', 'Al Ruwayyah', 'Al Sabkha', 'Al Safa', 'Al Sall',
            'Al Satwa', 'Al Shindagha', 'Al Souq Al Kabeer', 'Al Sufouh', 'Al Taween', 'Al Twar',
            'Al Warqa', 'Al Wasl', 'Al Wuheida', 'Al Zahra', 'Arabian Ranches', 'Barsha Heights',
            'Bluewaters Island', 'Bur Dubai', 'Burj Khalifa', 'Business Bay', 'Cedre Villas',
            'City Walk', 'Corniche Al Qawasim', 'Damac Hills', 'Deira', 'Discovery Gardens',
            'Dubai Academic City', 'Dubai Airport Free Zone', 'Dubai Creek Harbour', 'Dubai Design District',
            'Dubai Healthcare City', 'Dubai Hills Estate', 'Dubai Industrial City', 'Dubai International Airport',
            'Dubai International Financial Centre', 'Dubai Investment Park', 'Dubai Internet City',
            'Dubai Knowledge Village', 'Dubai Land', 'Dubai Marina', 'Dubai Maritime City', 'Dubai Media City',
            'Dubai Motor City', 'Dubai Outsource City', 'Dubai Silicon Oasis', 'Dubai South', 'Dubai Sports City',
            'Dubai Studio City', 'Emirates Hills', 'Emirates Road', 'Expo', 'Festival City', 'Green Community',
            'Hatta', 'International City', 'Jebel Ali', 'Jumeirah', 'Jumeirah Golf Estates', 'Jumeirah Islands',
            'Jumeirah Lakes Towers', 'Jumeirah Park', 'Jumeirah Village Circle', 'Karama', 'Khalifa Bin Zayed City',
            'Mall of the Emirates', 'Meydan', 'Mirdif', 'Mohammed Bin Rashid City', 'Muhaisnah', 'Nad Al Hammar',
            'Nad Al Sheba', 'Palm Jumeirah', 'Port Rashid', 'Ras Al Khor', 'Remraam', 'Sheikh Zayed Road',
            'Silicon Oasis', 'Springs', 'Tecom', 'Tilal Al Ghaf', 'Trade Centre', 'Umm Hurair', 'Umm Ramool',
            'Umm Suqeim', 'Warsan', 'Zaabeel'
        ]
    },
    'sharjah': {
        'name_ar': 'الشارقة',
        'name_en': 'Sharjah',
        'regions': [
            'Al noor island', 'Abu Shagara', 'Abu Tina', 'Al Abar', 'Al Atain', 'Al Azra',
            'Al Badea', 'Al Badea Palace', 'Al Bateen', 'Al Barashi', 'Al Bataeh', 'Al Bedi Suburb',
            'Al Falaj', 'Al Fayha', 'Al Fisht', 'Al Ghafiya', 'Al Ghubaibah', 'Al Goaz',
            'Al Hazana', 'Al Heerah Suburb', 'Al Jazeera', 'Al Jazat', 'Al Juraina', 'Al Khaledia',
            'Al Khalid Sea Port', 'Al Khezamia', 'Al Layyah', 'Al Majaz', 'Al Majarrah', 'Al Mamsha',
            'Al Mamzar', 'Al Manakh', 'Al Manazel', 'Al Mareija', 'Al Mirgab', 'Al Mowafjah',
            'Al Muweilah', 'Al Munay', 'Al Nahda', 'Al Nasserya', 'Al Nekhailat', 'Al Noof',
            'Al Qasba', 'Al Qulayaa', 'Al Qusais', 'Al Ramla', 'Al Ramtha', 'Al Rifaah',
            'Al Rolla', 'Al Sabkha', 'Al Sajaa', 'Al Seef', 'Al Shuwaihen', 'Al Soor',
            'Al Souq Al Kabeer', 'Al Taawun', 'Al Talaa', 'Al Tarfa', 'Al Turfah', 'Al Wahda',
            'Al Zahra', 'Al Zubair', 'Al Zubair Suburb', 'Al Zuhour', 'Al Majaz Waterfront',
            'Al Majaz Island', 'Al Majaz 1', 'Al Majaz 2', 'Al Majaz 3', 'Al Majaz 4',
            'Al Majaz 5', 'Al Majaz 6', 'Al Majaz 7', 'Al Majaz 8', 'Al Majaz 9', 'Al Majaz 10',
            'Al Majaz 11', 'Al Majaz 12', 'Al Majaz 13', 'Al Majaz 14', 'Al Majaz 15',
            'Al Majaz 16', 'Al Majaz 17', 'Al Majaz 18', 'Al Majaz 19', 'Al Majaz 20',
            'Al Majaz 21', 'Al Majaz 22', 'Al Majaz 23', 'Al Majaz 24', 'Al Majaz 25',
            'Al Majaz 26', 'Al Majaz 27', 'Al Majaz 28', 'Al Majaz 29', 'Al Majaz 30',
            'Al Majaz 31', 'Al Majaz 32', 'Al Majaz 33', 'Al Majaz 34', 'Al Majaz 35',
            'Al Majaz 36', 'Al Majaz 37', 'Al Majaz 38', 'Al Majaz 39', 'Al Majaz 40',
            'Al Majaz 41', 'Al Majaz 42', 'Al Majaz 43', 'Al Majaz 44', 'Al Majaz 45',
            'Al Majaz 46', 'Al Majaz 47', 'Al Majaz 48', 'Al Majaz 49', 'Al Majaz 50',
            'Al Majaz 51', 'Al Majaz 52', 'Al Majaz 53', 'Al Majaz 54', 'Al Majaz 55',
            'Al Majaz 56', 'Al Majaz 57', 'Al Majaz 58', 'Al Majaz 59', 'Al Majaz 60',
            'Al Majaz 61', 'Al Majaz 62', 'Al Majaz 63', 'Al Majaz 64', 'Al Majaz 65',
            'Al Majaz 66', 'Al Majaz 67', 'Al Majaz 68', 'Al Majaz 69', 'Al Majaz 70',
            'Al Majaz 71', 'Al Majaz 72', 'Al Majaz 73', 'Al Majaz 74', 'Al Majaz 75',
            'Al Majaz 76', 'Al Majaz 77', 'Al Majaz 78', 'Al Majaz 79', 'Al Majaz 80',
            'Al Majaz 81', 'Al Majaz 82', 'Al Majaz 83', 'Al Majaz 84', 'Al Majaz 85',
            'Al Majaz 86', 'Al Majaz 87', 'Al Majaz 88', 'Al Majaz 89', 'Al Majaz 90',
            'Al Majaz 91', 'Al Majaz 92', 'Al Majaz 93', 'Al Majaz 94', 'Al Majaz 95',
            'Al Majaz 96', 'Al Majaz 97', 'Al Majaz 98', 'Al Majaz 99', 'Al Majaz 100'
        ]
    },
    'ajman': {
        'name_ar': 'عجمان',
        'name_en': 'Ajman',
        'regions': [
            'Ajman Beach', 'Ajman Free Zone (AFZA)', 'Ajman Industrial 1', 'Ajman Industrial 2',
            'Ajman Port', 'Ajman Uptown', 'Al Alya', 'Al Amera', 'Al Bahya', 'Al Bustan',
            'Al Hamidiyah 1', 'Al Hamidiyah 2', 'Al Hamrya', 'Al Helio 1', 'Al Helio 2',
            'Al Jurf', 'Al Manama', 'Al Muntazi 1', 'Al Muntazi 2', 'Al Muwaihat 1',
            'Al Muwaihat 2', 'Al Muwaihat 3', 'Al Raqaib 1', 'Al Raqaib 2', 'Al Rashidiya 1',
            'Al Rashidiya 2', 'Al Rashidiya 3', 'Al Rawdha 1', 'Al Rawdha 2', 'Al Rawdha 3',
            'Al Rumailah 1', 'Al Rumailah 2', 'Al Rumailah 3', 'Al Safia', 'Al Safya Island',
            'Al Tallah 1', 'Al Tallah 2', 'Al Yasmeen', 'Al Zahya', 'Al Zora', 'Ammar Street',
            'Asyad Tower', 'China Mall', 'Corniche Ajman', 'Emirates City', 'King Faisal Street',
            'Liwara', 'Mushairef', 'Nakheel 1', 'Nakheel 2', 'Nuaimeya 1', 'Nuaimeya 2',
            'Nuaimeya 3', 'One Tower'
        ]
    },
    'ras_al_khaimah': {
        'name_ar': 'رأس الخيمة',
        'name_en': 'Ras Al Khaimah',
        'regions': [
            'Adhen Village', 'Ain Khatt', 'Airport Road', 'Al Batah', 'Al Burairat', 'Al Daith B',
            'Al Dar Al Bayda', 'Al Darbijaniyah', 'Al Dhait North', 'Al Dhait South', 'Al Dhait South A',
            'Al Dhait South B', 'Al Dhait South C', 'Al Dhait South D', 'Al Dhait South E', 'Al Driwyzah',
            'Al Duhaisah', 'Al Fahlain', 'Al Filayah', 'Al Ghail', 'Al Ghail East Free Zone', 'Al Ghail Free Zone',
            'Al Ghail Industrial Zone', 'Al Ghubb', 'Al Hanya', 'Al Harf', 'Al Hayl', 'Al Hudaibah',
            'Al Ijeli', 'Al Jeer', 'Al Juwais', 'Al Jazirah Al Hamra', 'Al Jazirah Industrial', 'Al Mafyar',
            'Al Mairid', 'New Al Maireed', 'Al Mamourah', 'Al Marjan Island', 'Al Mataf', 'Al Mushah',
            'Al Nadiyah', 'Al Nakheel', 'Al Nudood', 'Al Qarah', 'Al Qorm', 'Al Qusaidat', 'Al Rahba',
            'Ar Rams', 'Al Riffa', 'Al Sall', 'Al Seer', 'Al Seeh', 'Al Sharishah', 'Al Soor', 'Al Taween',
            'Al Turfah', 'Al Uraibi', 'Al Zahra', 'Aswaq Julfar', 'As Saadi', 'AZZAN', 'Bani Zayed',
            'Corniche Al Qawasim', 'Corniche Street', 'Dafan Al Khor', 'Dafan Al Nakheel', 'Dahan', 'Dhahiyyah',
            'Dibba Al Hisn', 'Dibba Al Hisn Industrial', 'Dibba Al Hisn Port', 'Dibba Al Hisn Port Industrial',
            'Dibba Al Hisn Port Industrial 1', 'Dibba Al Hisn Port Industrial 2', 'Dibba Al Hisn Port Industrial 3',
            'Dibba Al Hisn Port Industrial 4', 'Dibba Al Hisn Port Industrial 5', 'Dibba Al Hisn Port Industrial 6',
            'Dibba Al Hisn Port Industrial 7', 'Dibba Al Hisn Port Industrial 8', 'Dibba Al Hisn Port Industrial 9',
            'Dibba Al Hisn Port Industrial 10', 'Dibba Al Hisn Port Industrial 11', 'Dibba Al Hisn Port Industrial 12',
            'Dibba Al Hisn Port Industrial 13', 'Dibba Al Hisn Port Industrial 14', 'Dibba Al Hisn Port Industrial 15',
            'Dibba Al Hisn Port Industrial 16', 'Dibba Al Hisn Port Industrial 17', 'Dibba Al Hisn Port Industrial 18',
            'Dibba Al Hisn Port Industrial 19', 'Dibba Al Hisn Port Industrial 20', 'Dibba Al Hisn Port Industrial 21',
            'Dibba Al Hisn Port Industrial 22', 'Dibba Al Hisn Port Industrial 23', 'Dibba Al Hisn Port Industrial 24',
            'Dibba Al Hisn Port Industrial 25', 'Dibba Al Hisn Port Industrial 26', 'Dibba Al Hisn Port Industrial 27',
            'Dibba Al Hisn Port Industrial 28', 'Dibba Al Hisn Port Industrial 29', 'Dibba Al Hisn Port Industrial 30',
            'Dibba Al Hisn Port Industrial 31', 'Dibba Al Hisn Port Industrial 32', 'Dibba Al Hisn Port Industrial 33',
            'Dibba Al Hisn Port Industrial 34', 'Dibba Al Hisn Port Industrial 35', 'Dibba Al Hisn Port Industrial 36',
            'Dibba Al Hisn Port Industrial 37', 'Dibba Al Hisn Port Industrial 38', 'Dibba Al Hisn Port Industrial 39',
            'Dibba Al Hisn Port Industrial 40', 'Dibba Al Hisn Port Industrial 41', 'Dibba Al Hisn Port Industrial 42',
            'Dibba Al Hisn Port Industrial 43', 'Dibba Al Hisn Port Industrial 44', 'Dibba Al Hisn Port Industrial 45',
            'Dibba Al Hisn Port Industrial 46', 'Dibba Al Hisn Port Industrial 47', 'Dibba Al Hisn Port Industrial 48',
            'Dibba Al Hisn Port Industrial 49', 'Dibba Al Hisn Port Industrial 50', 'Dibba Al Hisn Port Industrial 51',
            'Dibba Al Hisn Port Industrial 52', 'Dibba Al Hisn Port Industrial 53', 'Dibba Al Hisn Port Industrial 54',
            'Dibba Al Hisn Port Industrial 55', 'Dibba Al Hisn Port Industrial 56', 'Dibba Al Hisn Port Industrial 57',
            'Dibba Al Hisn Port Industrial 58', 'Dibba Al Hisn Port Industrial 59', 'Dibba Al Hisn Port Industrial 60',
            'Dibba Al Hisn Port Industrial 61', 'Dibba Al Hisn Port Industrial 62', 'Dibba Al Hisn Port Industrial 63',
            'Dibba Al Hisn Port Industrial 64', 'Dibba Al Hisn Port Industrial 65', 'Dibba Al Hisn Port Industrial 66',
            'Dibba Al Hisn Port Industrial 67', 'Dibba Al Hisn Port Industrial 68', 'Dibba Al Hisn Port Industrial 69',
            'Dibba Al Hisn Port Industrial 70', 'Dibba Al Hisn Port Industrial 71', 'Dibba Al Hisn Port Industrial 72',
            'Dibba Al Hisn Port Industrial 73', 'Dibba Al Hisn Port Industrial 74', 'Dibba Al Hisn Port Industrial 75',
            'Dibba Al Hisn Port Industrial 76', 'Dibba Al Hisn Port Industrial 77', 'Dibba Al Hisn Port Industrial 78',
            'Dibba Al Hisn Port Industrial 79', 'Dibba Al Hisn Port Industrial 80', 'Dibba Al Hisn Port Industrial 81',
            'Dibba Al Hisn Port Industrial 82', 'Dibba Al Hisn Port Industrial 83', 'Dibba Al Hisn Port Industrial 84',
            'Dibba Al Hisn Port Industrial 85', 'Dibba Al Hisn Port Industrial 86', 'Dibba Al Hisn Port Industrial 87',
            'Dibba Al Hisn Port Industrial 88', 'Dibba Al Hisn Port Industrial 89', 'Dibba Al Hisn Port Industrial 90',
            'Dibba Al Hisn Port Industrial 91', 'Dibba Al Hisn Port Industrial 92', 'Dibba Al Hisn Port Industrial 93',
            'Dibba Al Hisn Port Industrial 94', 'Dibba Al Hisn Port Industrial 95', 'Dibba Al Hisn Port Industrial 96',
            'Dibba Al Hisn Port Industrial 97', 'Dibba Al Hisn Port Industrial 98', 'Dibba Al Hisn Port Industrial 99',
            'Dibba Al Hisn Port Industrial 100'
        ]
    },
    'fujairah': {
        'name_ar': 'الفجيرة',
        'name_en': 'Fujairah',
        'regions': [
            'Aqqa', 'Akamya', 'Al Abadilah', 'Al Badiyah', 'Al Barady - Kalba', 'Al Baraha - Kalba',
            'Al Faseel', 'Al Ghub', 'Al Ghurfah', 'Al Ghadf', 'Al Ghamrah', 'Al Gissemari',
            'Al Hala', 'Al Hanyah', 'Al Hayl Industrial Area', 'Al Heel', 'Al Hisn - Kalba',
            'Al Khalabiya', 'Al Mahatta - Kalba', 'Al Manzafah', 'Al Muhalab', 'Al Musalla - Kalba',
            'Al Nighala - Kalba', 'Al Qadisia - Kalba', 'Al Qasar', 'Al Raheeb', 'Al Raghelat',
            'Al Siji', 'Al Seih', 'Al Uwaid', 'Asimah', 'Bithnah', 'Bulaidha', 'Corniche',
            'Dadna', 'Dibba Al Fujairah', 'Dibba Al Hisn', 'Didna', 'Diftah', 'Emiri Divan',
            'Farfar', 'Fujairah City', 'Fujairah Free Zone', 'Fujairah International Airport',
            'Fujairah Port', 'Fujairah Rural', 'Haleefat', 'Hamad St (شارع)', 'Hayl',
            'Industrial Area', 'Isfay', 'Jazeerat Al Marjan', 'Kalba', 'Khor Kalba', 'Khorfakkan',
            'Kirat', 'Madhab', 'Maduk', 'Maidaq', 'Mamduh', 'Manama', 'Marbad', 'Masafi',
            'Mirbah', 'Municipality', 'Murashid', 'Nahwa', 'Old Fujairah', 'Qidfa', 'Qurrayah',
            'Ras Al Khaimah', 'Ras Al Khaimah Industrial', 'Ras Al Khaimah Port', 'Ras Al Khaimah Port Industrial',
            'Ras Al Khaimah Port Industrial 1', 'Ras Al Khaimah Port Industrial 2', 'Ras Al Khaimah Port Industrial 3',
            'Ras Al Khaimah Port Industrial 4', 'Ras Al Khaimah Port Industrial 5', 'Ras Al Khaimah Port Industrial 6',
            'Ras Al Khaimah Port Industrial 7', 'Ras Al Khaimah Port Industrial 8', 'Ras Al Khaimah Port Industrial 9',
            'Ras Al Khaimah Port Industrial 10', 'Ras Al Khaimah Port Industrial 11', 'Ras Al Khaimah Port Industrial 12',
            'Ras Al Khaimah Port Industrial 13', 'Ras Al Khaimah Port Industrial 14', 'Ras Al Khaimah Port Industrial 15',
            'Ras Al Khaimah Port Industrial 16', 'Ras Al Khaimah Port Industrial 17', 'Ras Al Khaimah Port Industrial 18',
            'Ras Al Khaimah Port Industrial 19', 'Ras Al Khaimah Port Industrial 20', 'Ras Al Khaimah Port Industrial 21',
            'Ras Al Khaimah Port Industrial 22', 'Ras Al Khaimah Port Industrial 23', 'Ras Al Khaimah Port Industrial 24',
            'Ras Al Khaimah Port Industrial 25', 'Ras Al Khaimah Port Industrial 26', 'Ras Al Khaimah Port Industrial 27',
            'Ras Al Khaimah Port Industrial 28', 'Ras Al Khaimah Port Industrial 29', 'Ras Al Khaimah Port Industrial 30',
            'Ras Al Khaimah Port Industrial 31', 'Ras Al Khaimah Port Industrial 32', 'Ras Al Khaimah Port Industrial 33',
            'Ras Al Khaimah Port Industrial 34', 'Ras Al Khaimah Port Industrial 35', 'Ras Al Khaimah Port Industrial 36',
            'Ras Al Khaimah Port Industrial 37', 'Ras Al Khaimah Port Industrial 38', 'Ras Al Khaimah Port Industrial 39',
            'Ras Al Khaimah Port Industrial 40', 'Ras Al Khaimah Port Industrial 41', 'Ras Al Khaimah Port Industrial 42',
            'Ras Al Khaimah Port Industrial 43', 'Ras Al Khaimah Port Industrial 44', 'Ras Al Khaimah Port Industrial 45',
            'Ras Al Khaimah Port Industrial 46', 'Ras Al Khaimah Port Industrial 47', 'Ras Al Khaimah Port Industrial 48',
            'Ras Al Khaimah Port Industrial 49', 'Ras Al Khaimah Port Industrial 50', 'Ras Al Khaimah Port Industrial 51',
            'Ras Al Khaimah Port Industrial 52', 'Ras Al Khaimah Port Industrial 53', 'Ras Al Khaimah Port Industrial 54',
            'Ras Al Khaimah Port Industrial 55', 'Ras Al Khaimah Port Industrial 56', 'Ras Al Khaimah Port Industrial 57',
            'Ras Al Khaimah Port Industrial 58', 'Ras Al Khaimah Port Industrial 59', 'Ras Al Khaimah Port Industrial 60',
            'Ras Al Khaimah Port Industrial 61', 'Ras Al Khaimah Port Industrial 62', 'Ras Al Khaimah Port Industrial 63',
            'Ras Al Khaimah Port Industrial 64', 'Ras Al Khaimah Port Industrial 65', 'Ras Al Khaimah Port Industrial 66',
            'Ras Al Khaimah Port Industrial 67', 'Ras Al Khaimah Port Industrial 68', 'Ras Al Khaimah Port Industrial 69',
            'Ras Al Khaimah Port Industrial 70', 'Ras Al Khaimah Port Industrial 71', 'Ras Al Khaimah Port Industrial 72',
            'Ras Al Khaimah Port Industrial 73', 'Ras Al Khaimah Port Industrial 74', 'Ras Al Khaimah Port Industrial 75',
            'Ras Al Khaimah Port Industrial 76', 'Ras Al Khaimah Port Industrial 77', 'Ras Al Khaimah Port Industrial 78',
            'Ras Al Khaimah Port Industrial 79', 'Ras Al Khaimah Port Industrial 80', 'Ras Al Khaimah Port Industrial 81',
            'Ras Al Khaimah Port Industrial 82', 'Ras Al Khaimah Port Industrial 83', 'Ras Al Khaimah Port Industrial 84',
            'Ras Al Khaimah Port Industrial 85', 'Ras Al Khaimah Port Industrial 86', 'Ras Al Khaimah Port Industrial 87',
            'Ras Al Khaimah Port Industrial 88', 'Ras Al Khaimah Port Industrial 89', 'Ras Al Khaimah Port Industrial 90',
            'Ras Al Khaimah Port Industrial 91', 'Ras Al Khaimah Port Industrial 92', 'Ras Al Khaimah Port Industrial 93',
            'Ras Al Khaimah Port Industrial 94', 'Ras Al Khaimah Port Industrial 95', 'Ras Al Khaimah Port Industrial 96',
            'Ras Al Khaimah Port Industrial 97', 'Ras Al Khaimah Port Industrial 98', 'Ras Al Khaimah Port Industrial 99',
            'Ras Al Khaimah Port Industrial 100'
        ]
    },
    'umm_al_quwain': {
        'name_ar': 'أم القيوين',
        'name_en': 'Umm Al Quwain',
        'regions': [
            'Al Abraq 1', 'Al Abraq 2', 'Al Athaib', 'Al Benaider', 'Al Bustan', 'Al Dar Al Bayda',
            'Al Door 1', 'Al Door 2', 'Al Ghafat', 'Al Hadeetha', 'Al Hamra', 'Al Hamriya',
            'Al Harmala', 'Al Heerah', 'Al Hoboob 1', 'Al Hoboob 2', 'Al Humaidi', 'Al Jurf 1',
            'Al Jurf 2', 'Al Jurf Industrial 1', 'Al Jurf Industrial 2', 'Al Jurf Industrial 3',
            'Al Khor', 'Al Madr 1', 'Al Madr 2', 'Al Madr 3', 'Al Maqta-a 1', 'Al Maqta-a 2',
            'Al Maqta-a 3', 'Al Medfeq', 'Al Meidan', 'Al Morgbat', 'Al Nabgghah', 'Al Nakheilah',
            'Al Neefah', 'Al Qarayen 1', 'Al Qarayen 2', 'Al Raas', 'Al Rahail', 'Al Ramlah 1',
            'Al Ramlah 2', 'Al Ramlah 3', 'Al Ras 1', 'Al Ras 2', 'Al Rawdha', 'Al Reqqah',
            'Al Salamah', 'Al Serra', 'Al Shareiah', 'Al Shebeakah', 'Al Shes', 'Al Sow',
            'Al Suaihat 1', 'Al Suaihat 2', 'Al Tayebah', 'Al Thaniyah', 'Batha Al Ali',
            'Emirates Modern Industrial Area (Umm Al Thuoob)', 'Falaj Al Mualla', 'Falaj Al Sheikh',
            'Green Belt', 'Hamriyah Free Zone Phase 1 (HFZA)', 'Hamriyah Free Zone Phase 2',
            'Old Umm Al Quwain', 'Oud Al Owaid', 'Ras Al Khaimah', 'Ras Al Khaimah Industrial',
            'Ras Al Khaimah Port', 'Ras Al Khaimah Port Industrial', 'Ras Al Khaimah Port Industrial 1',
            'Ras Al Khaimah Port Industrial 2', 'Ras Al Khaimah Port Industrial 3', 'Ras Al Khaimah Port Industrial 4',
            'Ras Al Khaimah Port Industrial 5', 'Ras Al Khaimah Port Industrial 6', 'Ras Al Khaimah Port Industrial 7',
            'Ras Al Khaimah Port Industrial 8', 'Ras Al Khaimah Port Industrial 9', 'Ras Al Khaimah Port Industrial 10',
            'Ras Al Khaimah Port Industrial 11', 'Ras Al Khaimah Port Industrial 12', 'Ras Al Khaimah Port Industrial 13',
            'Ras Al Khaimah Port Industrial 14', 'Ras Al Khaimah Port Industrial 15', 'Ras Al Khaimah Port Industrial 16',
            'Ras Al Khaimah Port Industrial 17', 'Ras Al Khaimah Port Industrial 18', 'Ras Al Khaimah Port Industrial 19',
            'Ras Al Khaimah Port Industrial 20', 'Ras Al Khaimah Port Industrial 21', 'Ras Al Khaimah Port Industrial 22',
            'Ras Al Khaimah Port Industrial 23', 'Ras Al Khaimah Port Industrial 24', 'Ras Al Khaimah Port Industrial 25',
            'Ras Al Khaimah Port Industrial 26', 'Ras Al Khaimah Port Industrial 27', 'Ras Al Khaimah Port Industrial 28',
            'Ras Al Khaimah Port Industrial 29', 'Ras Al Khaimah Port Industrial 30', 'Ras Al Khaimah Port Industrial 31',
            'Ras Al Khaimah Port Industrial 32', 'Ras Al Khaimah Port Industrial 33', 'Ras Al Khaimah Port Industrial 34',
            'Ras Al Khaimah Port Industrial 35', 'Ras Al Khaimah Port Industrial 36', 'Ras Al Khaimah Port Industrial 37',
            'Ras Al Khaimah Port Industrial 38', 'Ras Al Khaimah Port Industrial 39', 'Ras Al Khaimah Port Industrial 40',
            'Ras Al Khaimah Port Industrial 41', 'Ras Al Khaimah Port Industrial 42', 'Ras Al Khaimah Port Industrial 43',
            'Ras Al Khaimah Port Industrial 44', 'Ras Al Khaimah Port Industrial 45', 'Ras Al Khaimah Port Industrial 46',
            'Ras Al Khaimah Port Industrial 47', 'Ras Al Khaimah Port Industrial 48', 'Ras Al Khaimah Port Industrial 49',
            'Ras Al Khaimah Port Industrial 50', 'Ras Al Khaimah Port Industrial 51', 'Ras Al Khaimah Port Industrial 52',
            'Ras Al Khaimah Port Industrial 53', 'Ras Al Khaimah Port Industrial 54', 'Ras Al Khaimah Port Industrial 55',
            'Ras Al Khaimah Port Industrial 56', 'Ras Al Khaimah Port Industrial 57', 'Ras Al Khaimah Port Industrial 58',
            'Ras Al Khaimah Port Industrial 59', 'Ras Al Khaimah Port Industrial 60', 'Ras Al Khaimah Port Industrial 61',
            'Ras Al Khaimah Port Industrial 62', 'Ras Al Khaimah Port Industrial 63', 'Ras Al Khaimah Port Industrial 64',
            'Ras Al Khaimah Port Industrial 65', 'Ras Al Khaimah Port Industrial 66', 'Ras Al Khaimah Port Industrial 67',
            'Ras Al Khaimah Port Industrial 68', 'Ras Al Khaimah Port Industrial 69', 'Ras Al Khaimah Port Industrial 70',
            'Ras Al Khaimah Port Industrial 71', 'Ras Al Khaimah Port Industrial 72', 'Ras Al Khaimah Port Industrial 73',
            'Ras Al Khaimah Port Industrial 74', 'Ras Al Khaimah Port Industrial 75', 'Ras Al Khaimah Port Industrial 76',
            'Ras Al Khaimah Port Industrial 77', 'Ras Al Khaimah Port Industrial 78', 'Ras Al Khaimah Port Industrial 79',
            'Ras Al Khaimah Port Industrial 80', 'Ras Al Khaimah Port Industrial 81', 'Ras Al Khaimah Port Industrial 82',
            'Ras Al Khaimah Port Industrial 83', 'Ras Al Khaimah Port Industrial 84', 'Ras Al Khaimah Port Industrial 85',
            'Ras Al Khaimah Port Industrial 86', 'Ras Al Khaimah Port Industrial 87', 'Ras Al Khaimah Port Industrial 88',
            'Ras Al Khaimah Port Industrial 89', 'Ras Al Khaimah Port Industrial 90', 'Ras Al Khaimah Port Industrial 91',
            'Ras Al Khaimah Port Industrial 92', 'Ras Al Khaimah Port Industrial 93', 'Ras Al Khaimah Port Industrial 94',
            'Ras Al Khaimah Port Industrial 95', 'Ras Al Khaimah Port Industrial 96', 'Ras Al Khaimah Port Industrial 97',
            'Ras Al Khaimah Port Industrial 98', 'Ras Al Khaimah Port Industrial 99', 'Ras Al Khaimah Port Industrial 100'
        ]
    }
}

def get_emirates():
    """Get all emirates with their names."""
    return {key: {'name_ar': value['name_ar'], 'name_en': value['name_en']} 
            for key, value in EMIRATES_AND_REGIONS.items()}

def get_regions(emirate_key):
    """Get regions for a specific emirate."""
    return EMIRATES_AND_REGIONS.get(emirate_key, {}).get('regions', [])

def get_emirate_name(emirate_key, language='en'):
    """Get emirate name in specified language."""
    emirate = EMIRATES_AND_REGIONS.get(emirate_key, {})
    if language == 'ar':
        return emirate.get('name_ar', '')
    return emirate.get('name_en', '')
