# Generated by Django 5.2.4 on 2025-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected roles cannot be deleted', verbose_name='Protected Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('seller', 'Seller')], max_length=50, verbose_name='Role Type'),
        ),
    ]
