# Generated by Django 5.2.4 on 2025-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_is_protected_alter_role_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_type',
        ),
        migrations.AddField(
            model_name='permission',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('manage', 'Manage')], max_length=20, verbose_name='Permission Type'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_protected',
            field=models.BooleanField(default=True, help_text='Protected roles cannot be deleted', verbose_name='Protected Role'),
        ),
    ]
