# Generated by Django 5.2.4 on 2025-08-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_add_signals'),
        ('roles', '0003_remove_role_role_type_permission_model_name_and_more'),
    ]

    operations = [
    ]
