# Generated by Django 5.2.4 on 2025-08-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_add_admin_role'),
        ('roles', '0004_merge_20250802_0314'),
    ]

    operations = [
    ]
