# Generated by Django 5.2.4 on 2025-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_merge_0004_add_admin_role_0004_merge_20250802_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('specialist', 'Specialist'), ('assistant', 'Assistant'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Role Type'),
        ),
    ]
