# Generated by Django 5.0.2 on 2025-09-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_sourcing_followup_roles'),
        ('roles', '0006_role_role_type'),
    ]

    operations = [
    ]
