# Generated by Django 5.2.4 on 2025-07-18 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('business_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='business name')),
                ('residence_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='residence country')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('subscription_type', models.CharField(default='basic', max_length=50, verbose_name='subscription type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='subscription date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
