# Generated by Django 5.2.4 on 2025-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cancelled_reason_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_link',
            field=models.URLField(help_text='Product link is required', verbose_name='Store Link'),
        ),
    ]
