# Generated by Django 5.2.4 on 2025-08-22 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_store_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed')], default='seller_submitted', max_length=30, verbose_name='Workflow Status'),
        ),
        migrations.CreateModel(
            name='OrderWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed')], max_length=30)),
                ('to_status', models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed')], max_length=30)),
                ('notes', models.TextField(blank=True, verbose_name='Notes about the transition')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who made the change')),
            ],
            options={
                'verbose_name': 'Order Workflow Log',
                'verbose_name_plural': 'Order Workflow Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
