# Generated by Django 5.2.4 on 2025-08-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_expected_delivery_date_order_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priority',
        ),
    ]
