# Generated by Django 5.0.2 on 2025-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_priority_and_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(blank=True, help_text='Confirmed delivery area by call center', max_length=100, verbose_name='Delivery Area'),
        ),
        migrations.AlterField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], default='seller_submitted', max_length=30, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='orderworkflowlog',
            name='from_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderworkflowlog',
            name='to_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
