# Generated by Django 5.0.2 on 2025-09-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_delivery_area_alter_order_workflow_status_and_more'),
        ('sellers', '0015_product_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_orders', to='sellers.product', verbose_name='Legacy Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_review', 'Call Center Review'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], default='seller_submitted', max_length=30, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='orderworkflowlog',
            name='from_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_review', 'Call Center Review'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderworkflowlog',
            name='to_status',
            field=models.CharField(choices=[('seller_submitted', 'Seller Submitted'), ('callcenter_review', 'Call Center Review'), ('callcenter_approved', 'Call Center Approved'), ('pick_and_pack', 'Pick and Pack'), ('stockkeeper_approved', 'Stock Keeper Approved'), ('packaging_in_progress', 'Packaging In Progress'), ('packaging_completed', 'Packaging Completed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery In Progress'), ('delivery_completed', 'Delivery Completed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
