# Generated by Django 5.0.2 on 2025-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_product_alter_order_workflow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('no_answer_1st', 'No Answer - 1st Attempt'), ('no_answer_2nd', 'No Answer - 2nd Attempt'), ('no_answer_final', 'No Answer - Final Attempt'), ('postponed', 'Postponed'), ('invalid_number', 'Invalid Number'), ('call_back_later', 'Call Back Later'), ('escalate_manager', 'Escalate to Manager')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
