# Generated by Django 5.0.2 on 2025-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emirate',
            field=models.CharField(blank=True, help_text='UAE Emirate', max_length=50, verbose_name='Emirate'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, help_text='UAE Region within Emirate', max_length=50, verbose_name='Region'),
        ),
    ]
