# Generated by Django 5.0.2 on 2025-10-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_emirate_order_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Escalated At'),
        ),
        migrations.AddField(
            model_name='order',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Escalated By'),
        ),
        migrations.AddField(
            model_name='order',
            name='escalated_to_manager',
            field=models.BooleanField(default=False, verbose_name='Escalated to Manager'),
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=50, verbose_name='New Status')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='Change Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('is_manager_change', models.BooleanField(default=False, verbose_name='Is Manager Change')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Status Log',
                'verbose_name_plural': 'Status Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
