# Generated by Django 5.2.4 on 2025-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_escalation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postponed_until',
            field=models.DateTimeField(blank=True, help_text='Date and time when order should be processed', null=True, verbose_name='Postponed Until'),
        ),
    ]
