# Generated by Django 4.2.25 on 2025-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_postponed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address and building number', max_length=255, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, help_text='Area/Region within city', max_length=100, verbose_name='Area'),
        ),
    ]
