# Generated by Django 5.2.7 on 2025-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_street_address_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_back_time',
            field=models.DateTimeField(blank=True, help_text='Date and time for call back set by call center', null=True, verbose_name='Call Back Time'),
        ),
    ]
