# Generated by Django 5.2.7 on 2025-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_call_back_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_answer_time',
            field=models.DateTimeField(blank=True, help_text='Date and time for next call attempt when customer did not answer', null=True, verbose_name='No Answer Time'),
        ),
    ]
