# Generated by Django 5.2.4 on 2025-08-26 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('new_order', 'New Order'), ('order_status_changed', 'Order Status Changed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('inventory_low', 'Low Inventory'), ('inventory_out', 'Out of Stock'), ('user_approved', 'User Account Approved'), ('user_rejected', 'User Account Rejected'), ('system', 'System Notification'), ('workflow_update', 'Workflow Update'), ('delivery_update', 'Delivery Update'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed')], default='system', max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('target_role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Target Role')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Related Object Type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related Object ID')),
                ('related_url', models.URLField(blank=True, null=True, verbose_name='Related URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'), models.Index(fields=['target_role', 'created_at'], name='notificatio_target__51014c_idx')],
            },
        ),
    ]
