# Generated by Django 5.2.4 on 2025-08-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('product_pending', 'Product Pending Approval'), ('product_deleted', 'Product Deleted'), ('new_order', 'New Order'), ('order_status_changed', 'Order Status Changed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('inventory_low', 'Low Inventory'), ('inventory_out', 'Out of Stock'), ('user_approved', 'User Account Approved'), ('user_rejected', 'User Account Rejected'), ('system', 'System Notification'), ('workflow_update', 'Workflow Update'), ('delivery_update', 'Delivery Update'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('data_export', 'Data Export'), ('data_import', 'Data Import')], default='system', max_length=30, verbose_name='Type'),
        ),
    ]
